services:
  backend:
    build:
      context: ./backend
      dockerfile: ./dev.Dockerfile
    volumes:
      - ./backend:/usr/src/backend
    ports:
      - 3000:3000
  frontend:
    build:
      context: ./frontend
      dockerfile: ./dev.Dockerfile
    volumes:
      - ./frontend:/usr/src/frontend
    ports:
      - 5173:5173
