CREATE TABLE IF NOT EXISTS work_rights (
    work_id INTEGER NOT NULL REFERENCES works (id) ON DELETE CASCADE ON UPDATE CASCADE,
    user_id INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
    PRIMARY KEY (work_id, user_id)
);
