CREATE TABLE IF NOT EXISTS works (
    id INTEGER PRIMARY KEY NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    title TEXT NOT NULL,
    short_description TEXT NOT NULL,
    long_description TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS work_slug_index ON works ( slug );

CREATE TABLE IF NOT EXISTS work_attachments (
    id INTEGER PRIMARY KEY NOT NULL,
    work_id INTEGER NOT NULL REFERENCES works (id) ON DELETE CASCADE ON UPDATE CASCADE,
    attachment_kind VARCHAR(16) NOT NULL,
    content_type VARCHAR(64) NOT NULL,
    title TEXT,
    bytes_base64 TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS work_links (
    id INTEGER PRIMARY KEY NOT NULL,
    work_id INTEGER NOT NULL REFERENCES works (id) ON DELETE CASCADE ON UPDATE CASCADE,
    title TEXT NOT NULL,
    href TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS work_tags (
    id INTEGER PRIMARY KEY NOT NULL,
    work_id INTEGER NOT NULL REFERENCES works (id) ON DELETE CASCADE ON UPDATE CASCADE,
    tag TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS categories (
    id INTEGER PRIMARY KEY NOT NULL,
    portfolio_id INTEGER NOT NULL REFERENCES portfolios (id) ON DELETE CASCADE ON UPDATE CASCADE,
    title TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS works_in_categories (
    category_id INTEGER NOT NULL REFERENCES categories (id) ON DELETE CASCADE ON UPDATE CASCADE,
    work_id INTEGER NOT NULL REFERENCES works (id) ON DELETE CASCADE ON UPDATE CASCADE,
    PRIMARY KEY (category_id, work_id)
);
